name: "Build and push aspnet Docker image"

on:
  push:
    branches: ["*"]
    tags: ["*"]
  schedule:
    - cron: "0 0 * * 0"

env:
  IMAGE_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAME: aspnet
  IMAGE_TAG: 7.0.20-gdi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./dotnet/core/aspnet/gdi/Dockerfile
        platforms: |
            linux/amd64
            linux/arm64
        push: true
        tags: ${{ env.IMAGE_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

