name: "Build and push aspnet Docker image"

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Image tag"
        required: true
        type: string

env:
  IMAGE_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAME: aspnet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo build and push config info
        run: |
          echo "Image registry: $Image_Registry"
          echo "Image name: $Image_Name"
          echo "Image tag: $Image_Tag"
        env:
          Image_Registry: ${{ env.IMAGE_REGISTRY }}
          Image_Name: ${{ env.IMAGE_NAME }}
          Image_Tag: ${{ inputs.imageTag }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dotnet/core/aspnet/gdi/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ inputs.imageTag }}
