name: "Build and push minio Docker image"

on:
  push:
    branches: ["*"]
    tags: ["*"]
  schedule:
    - cron: "0 0 * * 0"

jobs:

  main:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Prepare build environment; build; push to Docker Hub, RedHat Quay"
        run: |
          IMAGE_REGISTRY='registry.cn-hangzhou.aliyuncs.com'
          IMAGE_TAG="20240611"

          docker buildx create --use
          
          docker version
          
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} $IMAGE_REGISTRY
          cd minio
          # 使用Dockerfile构建镜像并推送镜像到镜像仓库
          docker buildx build --push --platform 'linux/amd64' --tag "$IMAGE_REGISTRY/${{ env.GITHUB_ACTOR }}/minio:$IMAGE_TAG" --file Dockerfile .
